### ISSUE TITLE
Latest Version Still Crashes When Trying to Apply Jetpack to ConArm Chestplate

### ISSUE THREAD

**Issue by Doublehelix13** [TeamDman/PlusTiC#33]
plustic-8.0.3.jar
SimplyJetpacks2-1.12.2-2.2.20.0.jar

When placing a chestplate from Construct's Armory into an Armor Forge and attempting to add a Jetpack to it as a modifier, the game crashes.  The crash report is below.  Oddly, it's mentioning Baubles, which I do not have installed.  I'm going to try installing Baubles and see if that fixes it.

[crash-2021-06-02_04.18.37-client.txt](https://github.com/TeamDman/PlusTiC/files/6583350/crash-2021-06-02_04.18.37-client.txt)

**Comment by Doublehelix13** [comment]
Update:  Installing Baubles allows you to add the jetpack to a chestplate without the game crashing.  However, trying to wear the jetpack will still cause a crash.  
Baubles-1.12-1.5.2.jar

[crash-2021-06-02_04.35.29-client.txt](https://github.com/TeamDman/PlusTiC/files/6583431/crash-2021-06-02_04.35.29-client.txt)

**Comment by TeamDman** [comment]
Hopefully fixed in latest
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad/files/3645594
If not, can reopen

**Comment by Doublehelix13** [comment]
I tested it again with the latest version.  Firstly, when a jetpack is placed in the armor forge, the screen messes up like so:
![Screen Shot 2022-02-12 at 12 21 24 PM](https://user-images.githubusercontent.com/40927088/153723747-2e2ec76e-fe6f-4e93-9b81-58b1ead38ee4.png)
However, you can still click the slots where the chestplate and the jetpack are and remove them, fixing the issue.  You can also successfully create a chestplate with the jetpack applied.  However, trying to wear the chestplate still causes a crash.
[crash-2022-02-12_12.22.37-server.txt](https://github.com/TeamDman/PlusTiC/files/8054276/crash-2022-02-12_12.22.37-server.txt)
[crash-2022-02-12_12.22.44-client.txt](https://github.com/TeamDman/PlusTiC/files/8054277/crash-2022-02-12_12.22.44-client.txt)
It created two crash reports, one for the server and one for client, which I've personally never seen before.  They look similar to me but I thought I'd upload both just in case.  The crash reports mention Baubles like before.  I'll install Baubles and test again.

**Comment by Doublehelix13** [comment]
With Baubles installed, the visual bug above does not happen.  However, the game does still crash when the chestplate with a jetpack is worn.
[crash-2022-02-12_12.47.44-client.txt](https://github.com/TeamDman/PlusTiC/files/8054295/crash-2022-02-12_12.47.44-client.txt)
Also, here is my latest.log if that helps.
[latest.log](https://github.com/TeamDman/PlusTiC/files/8054299/latest.log)

**Comment by Doublehelix13** [comment]
Okay, this is embarrassing.  I updated PlusTiC in one of my modpacks, then decided to test it using a different modpack where it was NOT updated.  So the crash reports above came from the 8.0.3 version.  Unfortunately, the 8.0.4 version crashes on startup.
[crash-2022-02-13_09.53.31-client.txt](https://github.com/TeamDman/PlusTiC/files/8055994/crash-2022-02-13_09.53.31-client.txt)

**Comment by Pelotrio** [comment]
> Okay, this is embarrassing. I updated PlusTiC in one of my modpacks, then decided to test it using a different modpack where it was NOT updated. So the crash reports above came from the 8.0.3 version. Unfortunately, the 8.0.4 version crashes on startup. [crash-2022-02-13_09.53.31-client.txt](https://github.com/TeamDman/PlusTiC/files/8055994/crash-2022-02-13_09.53.31-client.txt)

My fix from the pull request is correct but the uploaded jar is not. I explained this in my comment here https://github.com/TeamDman/PlusTiC/pull/38#issuecomment-1038444842

**Comment by Doublehelix13** [comment]
I'll close this issue since it looks like the jetpack problem is fixed and the current crashing problem is unrelated.

**Comment by TeamDman** [comment]
Please try latest build, sorry for the issues
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad/files/3648592
